# Generated by Django 4.1.4 on 2023-06-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_orderitem_image_url"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PendingEmail",
        ),
    ]
