# Generated by Django 4.1.4 on 2023-08-10 09:41

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_delete_pendingemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=15, unique=True)),
                ('image', models.ImageField(upload_to=order.models.paymentQrUploadPath)),
            ],
        ),
    ]
