# Generated by Django 4.1.4 on 2023-08-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_paymentqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentqr',
            name='amount',
            field=models.CharField(help_text='Make sure that amount is in floting point representation. For example, input 100.0 to represent 100', max_length=15, unique=True),
        ),
    ]
