# Generated by Django 4.1.4 on 2023-06-15 14:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_cartitem_image_url_product_is_image_required_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="for_user_positions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=2),
                default=list,
                help_text="comma separated list: MB - member, CR - Core, JS - Joint Sec, FS - Finance Sec, GS - Gen Sec. Ex: GS,FS,JS,CR",
                size=6,
            ),
        ),
    ]
