# Generated by Django 4.1.4 on 2023-08-10 10:02

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_for_user_positions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_chart_url',
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=product.models.productImageUploadPath),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=product.models.productImageUploadPath),
        ),
        migrations.AddField(
            model_name='product',
            name='size_chart_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=product.models.productImageUploadPath),
        ),
    ]
